🔀 :: (#29) feedlike delete
team-xquare/v1-service-feed pull request #32
Opened 2022-10-24 14:17 UTC by jaemin05

close #29

2022-10-24 15:38 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 12:04 UTC, jhhong0509 requested changes
p1) 피드 좋아요를 feed 테이블에서 관리하려면 최소한 update할 때 lock이라도 걸으레이

2022-10-25 12:05 UTC, jhhong0509 requested changes

2022-10-25 12:05 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepositoryAdapter.java
> +    public void deleteFeedLike(Feed feed, FeedLike feedLike) {
p1) 여기 @Transactional 없음

2022-10-26 04:53 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/FeedLikeApi.java
> +    void deleteFeedLike(UUID feedLikeId);
p4) 네이밍

2022-10-26 04:53 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +        Feed feed = queryFeedSpi.queryFeedById(feedLikeId);
feed를 feedLikeId로 찾는게 맞아?

2022-10-26 04:53 UTC, leeseojune53 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/FeedEntity.java
> +    }
p1) 이거 likeCount는 회의떄 이야기 ㄱ ㄱ
정합성 깨지기 너무 쉬움

2022-11-16 07:33 UTC, jhhong0509 reviewed
왜 이슈들들 해결 안하고 Resolve만 누른거임?

2022-11-16 07:44 UTC, jaemin05 commented
> 왜 이슈들들 해결 안하고 Resolve만 누른거임?

pull을 했는데 push를 안했어요.. 죄송합니다.

2022-11-16 07:46 UTC, jhhong0509 reviewed
로직상 문제가 있을뿐더러 우리 전에 feedLikeCount 안쓰기로 하지 않음?

2022-11-16 08:05 UTC, jaemin05 commented
> 로직상 문제가 있을뿐더러 우리 전에 feedLikeCount 안쓰기로 하지 않음?

feedLikeCount는 고쳤는데 로직상에 문제가 있다는 말이 이해가 되지 않습니다..

2022-11-16 08:41 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-16 08:46 UTC, jhhong0509 commented
> > 로직상 문제가 있을뿐더러 우리 전에 feedLikeCount 안쓰기로 하지 않음?
> 
> feedLikeCount는 고쳤는데 로직상에 문제가 있다는 말이 이해가 되지 않습니다..

ㅇㅎ 아님 feedLikeCount 수정할 때 동시성 문제 생긴거때매 그럼

2022-11-16 08:48 UTC, jaemin05 commented
> > > 로직상 문제가 있을뿐더러 우리 전에 feedLikeCount 안쓰기로 하지 않음?
> 
> > 
> 
> > feedLikeCount는 고쳤는데 로직상에 문제가 있다는 말이 이해가 되지 않습니다..
> 
> 
> 
> ㅇㅎ 아님 feedLikeCount 수정할 때 동시성 문제 생긴거때매 그럼

넵 감사합니다

2022-11-16 08:52 UTC, jhhong0509 requested changes

2022-11-16 08:52 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw InvalidUserException.EXCEPTION;
p3) InvalidUser가 맞음? UnAuthorized는 인증 실패 의미하는데, UserId가 헤더로 넘어왔다는건 인증 성공이란 뜻이잖아

2022-11-16 08:52 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +        if (commandFeedLikeSpi.existsUser(userId)) {
p2) 그리고 피드 좋아요를 제거하는건데 이미 좋아요를 눌렀다고 InvalidUser를 띄우면 안되는거 아님? ! 빼먹은 것 같은데

2022-11-16 08:52 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
> +    Optional<FeedLikeEntity> findByFeed(FeedEntity feed);
p1) 피드 좋아요가 피드당 하나임?
List가 맞지 않나?

2022-11-16 10:09 UTC, jaemin05 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/domain/repository/FeedLikeRepository.java
> +    Optional<FeedLikeEntity> findByFeed(FeedEntity feed);
사용하는 곳이 없어서 우선 지우겠습니다

2022-11-16 10:44 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyPushedException.EXCEPTION;
오류명이 너무 모호함
이것만 봐서는 사용자가 뭘 이미 눌렀는지 절대 모름
그리고 한 오류가 두 개 이상의 역할을 하고있는 것 같은데 그냥 나누는게 낫지 않음?

2022-11-16 10:44 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/exception/UserAlreadyPushedException.java
> +        super(FeedLikeErrorCode.INVALID_USER);
이건 왜 안꿈? INVALID_USER

2022-11-16 11:12 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-16 12:27 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-17 01:26 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/57659252/202331183-55077437-5316-4c14-a494-f94c371ff3f7.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57659252/202331239-4b4c5136-b228-44fe-af9f-e6664189514e.png">
그리고 왜 하나는 과거형이고 하나는 현재형임?

2022-11-17 02:09 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-17 02:13 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
가장 큰 문제는 과거형이 아니라 이름이 이상한건디
피드 서비스에서 좋아요 눌렀더니 '사용자가 이미 삭제되었습니다' 라는 메세지가 나오는게 의미상 맞는거임?

2022-11-17 05:30 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
이거 UnResolve로 바꿨는데 왜 자꾸 Resolve 눌림?

2022-11-17 08:19 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
이거 Exception 이름 애들들이랑 토론해서 오셈 @jaemin05

2022-11-17 08:20 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
넵

2022-11-17 08:52 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-17 08:59 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-17 13:07 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
> +            throw UserAlreadyDeleteException.EXCEPTION;
FeedLikeNotExistsException와 FeedLikeExistsException으로 하기로 했어요

2022-11-17 14:37 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-18 00:45 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/error/FeedLikeErrorCode.java
> +    FEED_LIKE_NOT_EXISTS(409, "Feed Like Not Exists");
404나 409 둘중에 토론해보면 좋을 거 같은데?

2022-11-18 01:19 UTC, oliver37632 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/api/impl/FeedLikeApiImpl.java
>      private final SecuritySpi securitySpi;
여기 한 줄 내려야하는거 아님?

2022-11-18 10:34 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feedlike/error/FeedLikeErrorCode.java
> +    FEED_LIKE_NOT_EXISTS(409, "Feed Like Not Exists");
Feed Like Not Exists만 404로 바꾸려고 하는데 뭐가 더 가까울까요..?

2022-11-21 00:26 UTC, lyutvs commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feedlike/web/WebFeedLikeAdapter.java
> +    @PostMapping("/{feed-like-uuid}")
취소인데 Post가 맞아..?

2022-11-21 00:28 UTC, oliver37632 approved these changes

2022-11-21 00:30 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-21 00:32 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-21 03:11 UTC, lyutvs approved these changes

2022-11-24 09:12 UTC, eogus2513 approved these changes

2022-11-24 11:52 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-29 12:35 UTC, merged

2022-11-29 13:10 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃