🔀 :: (#34) 댓글 조회하기
team-xquare/v1-service-feed pull request #39
Opened 2022-12-01 05:09 UTC by jaemin05

close #34 

현재 댓글을 조회할 때 유저 정보를 일일이 가져오도록 만들었는데 이렇게 하면 통신이랑 네트워크 관련 비용이 많이 발생할 거 같아요
그래서 생각해본 게 user API를 호출 할 때  user_id를 list로 전달하고 객체를 list로 전달 받는 것을 생각했는데 어떻게 생각하나요?

2022-12-01 05:16 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-01 05:17 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-01 05:30 UTC, jhhong0509 requested changes

2022-12-01 05:30 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
> +        this.createdAt = createdAt;
p2) 이건 왜 update하는거임? updatedAt도 아니고

2022-12-01 05:30 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
> +        UserInfoResponse response = userInfoClient.getUserInfo(comment.getUserId());
이거 그래서 내가 슬랙에 여러 사용자 조회 API 없냐고 물어봤는데 있다매

2022-12-01 05:30 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/feign/client/UserInfoClient.java
> +@FeignClient(name = "userInfoClient", url = "https://stag-api.xquare.app/users/id/{userId}")
p1) 이거 Cloud Config에서 가져오도록 바꿔야됨

2022-12-01 05:30 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/response/CommentDomainElement.java
> +public class CommentDomainElement {
Element는 무슨 의미로 붙인거임?

2022-12-01 05:30 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
> +        UserInfoResponse response = userInfoClient.getUserInfo(comment.getUserId());
그리고 builder는 builder 역할만 해야지 왜 사용자 정보까지 들고오는겨

2022-12-01 06:47 UTC, jaemin05 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
> +        UserInfoResponse response = userInfoClient.getUserInfo(comment.getUserId());
형님.. 저는 잘못 이해하고 있었어요. 여러 사용자 조회 API 는 없어요. 죄송합니다.. 
만들겠습니다.

2022-12-01 06:47 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/dto/response/CommentDomainElement.java
> +public class CommentDomainElement {
Response안에서 List 형태로 사용하려고 만들었습니다.

2022-12-01 06:47 UTC, jaemin05 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/repository/CommentRepositoryAdapter.java
> +        UserInfoResponse response = userInfoClient.getUserInfo(comment.getUserId());
builder도 수정하겠습니다.

2022-12-01 06:47 UTC, jaemin05 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
> +        this.createdAt = createdAt;
댓글 수정할 때 댓글 단 시간을 업데이트하려고 했습니다.
LastUpdatedAt으로 바꿀까요?

2022-12-01 07:05 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
> +        this.createdAt = createdAt;
updated_at으로 ㄱ

2022-12-02 01:18 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-05 13:39 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/feign/client/UserInfoClient.java
> +@FeignClient(name = "userInfoClient", url = "https://stag-api.xquare.app/users/id/{userId}")
이거 url cloudConfig로 가져오라는 말이죠?

2022-12-06 01:14 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/feign/client/UserInfoClient.java
> +@FeignClient(name = "userInfoClient", url = "https://stag-api.xquare.app/users/id/{userId}")
맞음

2022-12-07 23:19 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-08 12:57 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +                .collect(Collectors.toMap(User::getId, user -> user, (userId, user) -> user));
이거 생각 해보니깐 HashMap으로 해야 할듯

2022-12-08 12:57 UTC, eogus2513 commented on feed-infrastructure/build.gradle
> +
줄바꿈 하나 줄여줘요

2022-12-08 12:57 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/comment/domain/CommentEntity.java
> +        this.updatedAt = updatedAt;
이거는 우리쪽에서 찍어주면 더 좋을 듯

2022-12-08 13:03 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/CommentApi.java
> +    List<CommentDomainElement> queryComment(UUID feedId);
이거 method명을 조금 더 이해하기 쉽게 작성하면 좋을 거 같아요

2022-12-08 13:53 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-08 23:48 UTC, lyutvs commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +                        .updatedAt(LocalDateTime.now())
이게 맞나..? 수정한 시간 받아와서 넣어야 할것 같은데

2022-12-09 00:18 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +                        .updatedAt(LocalDateTime.now())
댓글 생성할 때는 수정 시간이랑 생성 시간 똑같이 해도 되지 않나??

2022-12-09 00:57 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-09 01:01 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-09 01:31 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-09 01:56 UTC, jhhong0509 approved these changes

2022-12-09 01:57 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
>      }
어라 이 PR 내용은 아닌데 우리 수정 / 삭제할 때 인가 로직은 어딨음?

2022-12-09 04:35 UTC, eogus2513 approved these changes

2022-12-09 04:36 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
>      }
이번 pr 머지하고 이슈 파서 수정하겠습니다.

2022-12-09 04:36 UTC, merged

2022-12-09 05:22 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃