🔀 :: (#43) 피드&댓글 인가 설정하기
team-xquare/v1-service-feed pull request #44
Opened 2022-12-10 14:41 UTC by jaemin05

close #43

2022-12-11 02:49 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +    }
이게 지금 CommnetApiImpl이랑 FeedApiImpl에서 동일한 코드로 사용되고 있는데 하나로 합치면 어떨까요?

2022-12-11 09:25 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +    }
user에다가 파서 만들까요?

2022-12-12 01:16 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/error/UserErrorCode.java
> +    UNAUTHORIZED_USER(403, "Unauthorized User");
UnAuthorized가 아니라 Forbidden 아님?

2022-12-12 03:35 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-12 06:33 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-12 14:15 UTC, leeseojune53 requested changes

2022-12-12 14:15 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +    }
p2) 하나로 합치고 method 명 변경. isMine은 boolean 반환하는 뉘앙스임
valid라던가 그런 갬성이면 좋을듯

2022-12-13 01:31 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/error/UserErrorCode.java
> +    UNAUTHORIZED_USER(403, "Unauthorized User");
여기만 고치지 말고 Exception 이름같은것도 다 고쳐야지

2022-12-13 05:27 UTC, jhhong0509 requested changes

2022-12-13 05:27 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/CommentUserSpi.java
> +    void checkValidUser(UUID userId, UUID currentUserId);
p2) 이게 Spi로 빠져야 하는 이유는 잘 모르겠는데
명백히 비지니스 로직중 하나고 던지는 오류도 비지니스 오류 아님?

2022-12-13 10:37 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/spi/CommentUserSpi.java
> +    void checkValidUser(UUID userId, UUID currentUserId);
domain 단에서 user안에 util 패키지 파서 할까요?

2022-12-13 11:55 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-14 01:11 UTC, jhhong0509 requested changes

2022-12-14 01:11 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/util/UserUtil.java
> +    }
p1) Bean 등록은 어디갔누

2022-12-14 01:43 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/util/UserUtil.java
> +    }
Domain단에서는 @component가 안 먹히는데 Infrastructure 단에 impl을 만들어서 Bean등록해야 하나요?

2022-12-14 08:16 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/util/UserUtil.java
> +    }
구현은 static 메소드로 만들든 뭐든 알아서 하고 일단 API가 동작을 안하잖어

2022-12-15 11:34 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-16 01:08 UTC, jhhong0509 approved these changes

2022-12-16 02:42 UTC, eogus2513 approved these changes

2022-12-16 02:43 UTC, lyutvs approved these changes

2022-12-16 02:52 UTC, jhhong0509 approved these changes

2022-12-17 13:20 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +        commentUserSpi.checkValidUser(comment.getUserId(), currentUserId);
checkValid 어감이 좀 이상한듯

2022-12-18 13:20 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +        commentUserSpi.checkValidUser(comment.getUserId(), currentUserId);
userVerification는 어떨까요?
![image](https://user-images.githubusercontent.com/89118999/208300650-34605c89-4860-4f7d-9fb3-2c389f35d3e7.png)

2022-12-21 05:43 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +        commentUserSpi.checkValidUser(comment.getUserId(), currentUserId);
![image](https://user-images.githubusercontent.com/89118999/208830261-7a190e16-5f54-43a5-8f62-42ca30e6aab9.png)
user validation은 어떨까요??

2022-12-21 05:44 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +        commentUserSpi.checkValidUser(comment.getUserId(), currentUserId);
validateUserId나 checkUserId 이런게 낫지 않을까
서준이가 말한건 checkValid를 같이 써서 그런 것 같은데

2022-12-21 05:46 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/comment/api/impl/CommentApiImpl.java
> +        commentUserSpi.checkValidUser(comment.getUserId(), currentUserId);
애들이랑 회의 해본 결과 validateUserId로 변경하기로 했습니다.

2022-12-21 05:51 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-21 05:54 UTC, jhhong0509 approved these changes

2022-12-21 05:54 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-21 05:54 UTC, eogus2513 approved these changes

2022-12-21 05:58 UTC, eogus2513 approved these changes

2022-12-21 06:04 UTC, lyutvs approved these changes

2022-12-21 06:07 UTC, oliver37632 approved these changes

2022-12-21 06:08 UTC, leeseojune53 approved these changes
두 개 코드가 거의 동일한 것 같은데 템플릿 메서드 패턴같은 패턴을 도전적으로 적용해봐도 좋은 경험이될듯

2022-12-21 06:12 UTC, jaemin05 commented
> 두 개 코드가 거의 동일한 것 같은데 템플릿 메서드 패턴같은 패턴을 도전적으로 적용해봐도 좋은 경험이될듯

우선 머지하고 새로 이슈파서 작업하겠습니다.

2022-12-21 06:15 UTC, merged

2022-12-21 06:22 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃