🔀 :: (#54) 피드 이미지 업데이트 API
team-xquare/v1-service-feed pull request #59
Opened 2022-12-30 15:10 UTC by eogus2513

close #54

2022-12-30 15:10 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 15:20 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 15:27 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 15:28 UTC, leeseojune53 requested changes

2022-12-30 15:28 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/dto/request/DomainUpdateFeedImageRequest.java
> +public class DomainUpdateFeedImageRequest {
p3) 네이밍 왜이럼?

2022-12-30 15:28 UTC, leeseojune53 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedImageApiImpl.java
> +        }
p2) 여기 로직 싹 버리자 뭘 하는 로직인지도 안보이고, 왜 저렇게 짠건지도 모르겠음
차라리 request foreach 돌면서 feedImageList.contains로 찾는게 나을듯

2022-12-30 15:46 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 15:51 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 15:52 UTC, leeseojune53 approved these changes

2022-12-30 15:53 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-30 16:29 UTC, jaemin05 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedImageApiImpl.java
> +        commandFeedImageSpi.saveAllFeedImage(feedImageList);
save랑 delete를 묶기만 한 거 아닌가요..?

2022-12-31 05:32 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedImageApiImpl.java
> +        commandFeedImageSpi.saveAllFeedImage(feedImageList);
API 로직을 저렇게 수정한 이유는 이미지가 동일할 때는 안들어온다는 가정하에 진행하였으며, for문을 돌면서 이미지 url이 같은지 확인하는 것보다 delete를 하고 insert를 하는 과정이 더 괜찮을 거 같아 이 방법을 선택하였습니다.

2022-12-31 06:31 UTC, jhhong0509 approved these changes
LGTM

2022-12-31 06:32 UTC, merged

2022-12-31 06:33 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-02 01:15 UTC, jaemin05 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/domain/repository/FeedImageRepository.java
> +    void deleteByFeedEntity(FeedEntity feedEntity);
이거 어디서 사용하나요?