🔀 ::(#48) 피드 생성 api 수정
team-xquare/v1-service-feed pull request #63
Opened 2023-01-02 02:19 UTC by oliver37632

close #49

2023-01-02 02:20 UTC, eogus2513 reviewed
이거 권한 검사 로직은 없는거야?

2023-01-02 02:22 UTC, oliver37632 commented
> 이거 권한 검사 로직은 없는거야?

검사하는거 authorization에서 하는걸로 하는거 아니였어?

2023-01-02 02:23 UTC, eogus2513 commented
> > 이거 권한 검사 로직은 없는거야?
> 
> 검사하는거 authorization에서 하는걸로 하는거 아니였어?

고걸 요청하는 API가 없는데?

2023-01-02 02:44 UTC, lyutvs commented
SecurityContextHolder에 있는걸로 권한 비교 하거나 SecuritConfig 쪽에서 하던지 해야 할듯?

2023-01-02 02:46 UTC, oliver37632 commented
> SecurityContextHolder에 있는걸로 권한 비교 하거나 SecuritConfig 쪽에서 하던지 해야 할듯?

해줘 찡찡

2023-01-02 11:45 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-03 02:08 UTC, jhhong0509 requested changes

2023-01-03 02:08 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
> +        List<UserAuthorization> authorizations = new ArrayList<>(Set.of(STD, STC, STA, DOD, DOS, CLL));
걍 List.of 하면 되는거 아님?

2023-01-03 02:08 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/error/UserErrorCode.java
> +    INVALID_ROLE(401, "Invalid Role");
Invalid Role이면 403 아님?

2023-01-03 02:08 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/exception/InvalidRoleException.java
> +
lint

2023-01-03 02:08 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
>      @Override
lint

2023-01-03 02:08 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
>      @Override
p1) 그리고 요청마다 SecurityContextHolder.getContext를 해야지 private final 변수로 박아두면 어캄?

2023-01-03 02:08 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +        }
이건 왜 하나라도 다르면 오류를 뱉는거임?
하나라도 같으면 괜찮아야하는거 아닌가?

2023-01-03 06:06 UTC, lyutvs commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/api/impl/FeedApiImpl.java
> +        List<UserAuthorization> authorizations = new ArrayList<>(Set.of(STD, STC, STA, DOD, DOS, CLL));
넵

2023-01-03 06:07 UTC, lyutvs commented on feed-domain/src/main/java/com/xquare/v1servicefeed/user/exception/InvalidRoleException.java
> +
넵

2023-01-03 06:13 UTC, lyutvs commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +        }
수정 했습니다.

2023-01-03 06:13 UTC, lyutvs commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
>      @Override
넵

2023-01-03 06:18 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +            if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().toString().equals(authority.toString())) {
List 타입에다가 toString해서 비교하면 당연히 false 아님?
getAuthorities 해서 반복문 돌면서 비교해야지

2023-01-03 14:58 UTC, lyutvs commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +        Collection<? extends GrantedAuthority> authorities = SecurityContextHolder.getContext().getAuthentication().getAuthorities();
이쪽 변수는 형변환 해서 하는게 좋을까요 아니면 지금이 더 좋을까요?

2023-01-03 15:22 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-03 23:40 UTC, jaemin05 commented
"authority": "학생회"
SaveFeedRequest에 위에처럼 authority 필요해요

2023-01-04 11:49 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-04 11:51 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-04 13:39 UTC, eogus2513 approved these changes

2023-01-04 14:11 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-05 01:22 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +    public boolean isValidateUserAuthority(String categoryName) {
이런식으로 'category만을 위한 SecurityAdapter 메소드'는 재사용성이 너무 떨어짐
차라리 target 권한만 파라미터로 받아서 비교하는게 나을 것 같은데
얘가 카테고리쪽이랑 결합도를 가질 이유는 없잖아

2023-01-05 01:23 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
그러고보니 authorityId는 뭐임?

2023-01-06 06:14 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +    public boolean isValidateUserAuthority(String categoryName) {
그러면 해당하는 권한을 파라미터로 같이 넘겨서 진행할까요?

2023-01-06 06:18 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
클라이언트쪽에서 요청하는 권한이랑 헤더의 값이 맞는지 확인하려고 했는데 그냥 요청이 들어오면 category에 따라서 권한 List로 넘겨서 있으면 생성하는 쪽으로 변경하는 쪽으로 할까요?

2023-01-06 06:33 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
ㅖㅏ

2023-01-06 06:33 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/configuration/security/SecurityAdapter.java
> +    public boolean isValidateUserAuthority(String categoryName) {
ㅖㅏ

2023-01-06 08:10 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
해당 유저가 작성할 수 있는 사람인지 확인하려고 처음에는 넣었던 건데 그냥 헤더에 있는 값으로 할 수 있는지만 판단하고 하는 걸로 해도 될거 같아요

2023-01-06 08:13 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
근데 조금 더 생각해봤는데 저희가 동아리에 대해서 작성했다고 했을 때 feed에서 보여주면 정보를 Pick에서 동아리 정보를 들고와서 진행해야 하는데 그때 해당 동아리가 어떤 동아리인지 어떻게 알 수 있을까요?

2023-01-07 05:56 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-07 07:36 UTC, eogus2513 approved these changes

2023-01-07 10:18 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
몰루? 컬럼 추가 해야할지도?

2023-01-08 10:55 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
결함이 있는데 왜 resolve 누름?

2023-01-08 12:28 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
아아 해결한줄 알았어요...

2023-01-08 12:34 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-08 12:34 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
생각해보니깐 헤더에 이미 사용자의 대한 권한을 넘겨주고, 카테고리만 받아도 권한 검사를 하여 처리할 수 있어서 authority_id 삭제하는 걸로 결정해서 삭제했습니다.

2023-01-08 12:43 UTC, jhhong0509 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
그게 아니라 니가 말한대로 '동아리에 글쓰기'를 했는데 피드 목록 볼 때 '내 동아리의 글 목록 보기' 하려면 답이 없잖어

2023-01-09 05:00 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-10 00:49 UTC, lyutvs approved these changes

2023-01-10 00:55 UTC, jaemin05 approved these changes

2023-01-10 01:25 UTC, jhhong0509 commented
@eogus2513
애들들한테 그때 토의했던거 공유 안했음?

2023-01-10 01:27 UTC, eogus2513 commented on feed-infrastructure/src/main/java/com/xquare/v1servicefeed/feed/web/dto/request/WebCreateFeedRequest.java
> +    private UUID authorityId;
> @eogus2513 애들들한테 그때 토의했던거 공유 안했음?

아직 저희가 못모여서 전달을 못해서 대충 설명은 해줬어요

2023-01-10 01:28 UTC, eogus2513 commented
> @eogus2513 애들들한테 그때 토의했던거 공유 안했음?

아직 저희가 못모여서 대충 페메로 전달은 했는데 자세하게 전달 못해서 모이는데로 전달할게요

2023-01-10 12:30 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
> +    private final Integer likeCount;
이거 안쓰기로 하지 않았나?

2023-01-11 00:48 UTC, eogus2513 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
> +    private final Integer likeCount;
likeCount 말씀하는거에요? 아니면 type 말하는 거에요?

2023-01-11 01:42 UTC, jhhong0509 commented on feed-domain/src/main/java/com/xquare/v1servicefeed/feed/Feed.java
> +    private final Integer likeCount;
likeCount

2023-01-11 02:28 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-11 03:24 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-11 06:20 UTC, jaemin05 approved these changes

2023-01-11 07:18 UTC, jhhong0509 approved these changes

2023-01-11 11:26 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2023-01-11 14:19 UTC, merged

2023-01-11 15:43 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃